name: BacklogAIiOS
options:
  bundleIdPrefix: com.backlogai

targets:
  BacklogAIiOS:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: BacklogAIApp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.backlogai.ios
        INFOPLIST_FILE: BacklogAIApp/Info.plist
        SWIFT_VERSION: "5.9"
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        FRAMEWORK_SEARCH_PATHS: "$(SRCROOT)/../composeApp/build/bin/iosSimulatorArm64/debugFramework"
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks"
        OTHER_LDFLAGS: "-framework ComposeApp"
    preBuildScripts:
      - name: Build Compose framework
        script: |
          set -e
          cd "$SRCROOT/.."
          ./gradlew :composeApp:linkDebugFrameworkIosSimulatorArm64
        basedOnDependencyAnalysis: false
    dependencies:
      - framework: ../composeApp/build/bin/iosSimulatorArm64/debugFramework/ComposeApp.framework
